language: node_js
node_js:
- '0.10'
services:
- mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in id_rsa.enc -out id_rsa -d
- npm install -g grunt-cli bower protractor jasmine
- bower install
- chmod +x bin/importdb
- chmod +x bin/test
- webdriver-manager update --standalone
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
- sudo apt-add-repository ppa:jon-severinsson/ffmpeg
- sudo apt-get update
- sudo apt-get install ffmpeg libavcodec-extra-53
after_success:
- chmod +x misc/deploy.sh
- misc/deploy.sh
