language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in id_rsa.enc -out id_rsa -d
- npm install -g grunt-cli bower
after_success:
- chmod +x deploy.sh
- ./deploy.sh
